MarkPadServer/MarkPadServer/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MarkPadServer.Controllers
{
    using MarkPadServer.PageStore;

    public class HomeController : Controller
    {
        private readonly IPageStore pageStore;

        public HomeController(IPageStore pageStore)
        {
            this.pageStore = pageStore;
        }

        public ActionResult Index()
        {
            return View(pageStore.ListPages());
        }
    }
}

MarkPadServer/MarkPadServer/Controllers/PagesController.cs
using System.Web.Mvc;

namespace MarkPadServer.Controllers
{
    using MarkPadServer.PageStore;

    public class PagesController : Controller
    {
        private readonly IPageStore pageStore;

        public PagesController(IPageStore pageStore)
        {
            this.pageStore = pageStore;
        }

        public ActionResult ViewPage(string name)
        {
            /* var markdown = new Markdown();
            using(var textStream = System.IO.File.OpenText(Server.MapPath("~/MdPages/" + name + ".md")))
            {
                var htmlResult = markdown.Transform(textStream.ReadToEnd());
                return View(htmlResult);
            } */
            var content = pageStore.GetPageContent(name);
            return this.View((object)content);
        }
    }
}

MarkPadServer/MarkPadServer/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Http;

namespace MarkPadServer.Controllers
{
    public class ValuesController : ApiController
    {
        // GET /api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET /api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST /api/values
        public void Post(string value)
        {
        }

        // PUT /api/values/5
        public void Put(int id, string value)
        {
        }

        // DELETE /api/values/5
        public void Delete(int id)
        {
        }
    }
}

MarkPadServer/MarkPadServer/Views/Home/Index.cshtml
@model IEnumerable<string>

<h1>MarkPad Server</h1>
<h3>Pages</h3>
<ul>
    @foreach(var page in Model)
    {
        <li>
            @Html.ActionLink(page, "ViewPage", "Pages", new {name = page}, null)
        </li>
    }
</ul>

MarkPadServer/MarkPadServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
</head>
<body>
    @RenderBody()
</body>
</html>